#!/bin/sh

# settings for common commands
alias \
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias	bc="bc -ql"
alias	mkd="mkdir -pv"
alias ls="ls -hN --color=auto --group-directories-first"

# application aliases
alias v="$EDITOR"
alias m="mpv"
alias p="sudo pacman"
alias nb="newsboat"
alias z="zathura"

# git aliases
alias g="git"
alias gst="git status"
alias gc="git commit"
alias ga="git add"
alias gpl="git pull"
alias gpom="git pull origin master"
alias gpu="git push"
alias gpuom="git push origin master"
alias gd="git diff"
alias gch="git checkout"
alias gnb="git checkout -b"
alias gac="git add . && git commit"
alias grs="git restore --staged ."
alias gre="git restore"
alias gr="git remote"
alias gcl="git clone"
alias glg="git log --graph --abbrev-commit --decorate --format=format:'%C(bold green)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold yellow)(%ar)%C(reset)%C(auto)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"
alias gt="git ls-tree -r master --name-only"
alias grm="git remote"
alias gb="git branch"
alias gf="git fetch"
