#!/bin/sh

# settings for common commands
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias bc="bc -ql"
alias mkd="mkdir -pv"
alias ls="exa --icons --group-directories-first"
alias lf="lfcd"
alias locate="plocate"
alias tp="trash-put"
alias tpr="trash-restore"
alias cat='bat'
alias grep='grep --color=always'

# windows to swallow
alias mpv="swallow mpv"
alias zathura="swallow zathura"
alias feh="swallow feh"

# application aliases
alias v="$EDITOR"
alias vim="$EDITOR"
alias p="paru"
alias nb="newsboat"
alias za="zathura"
alias code="vscodium"
alias ytdl="yt-dlp --no-mtime"

# aliases to clean up home directory
alias monerod=monerod --data-dir "$XDG_DATA_HOME"/bitmonero
alias svn="svn --config-dir $XDG_CONFIG_HOME/subversion"
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"

# git aliases
alias g="git"
alias gst="git status"
alias gc="git commit"
alias ga="git add"
alias gpl="git pull"
alias gpom="git pull origin master"
alias gpu="git push"
alias gpuom="git push origin master"
alias gd="git diff"
alias gch="git checkout"
alias gnb="git checkout -b"
alias gac="git add . && git commit"
alias grs="git restore --staged ."
alias gre="git restore"
alias gr="git remote"
alias gcl="git clone"
alias glg="git log --graph --abbrev-commit --decorate --format=format:'%C(bold green)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold yellow)(%ar)%C(reset)%C(auto)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"
alias gt="git ls-tree -r master --name-only"
alias grm="git remote"
alias gb="git branch"
alias gf="git fetch"

# aliases for dotfiles git bare repo
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias cfa='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME add'
alias cfc='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME commit'
alias cfp='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME push'
