systemctl --user import-environment DISPLAY

setxkbmap -option "caps:swapescape"

sxhkd &
picom --experimental-backends &
redshift &
xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output HDMI1 --mode 1920x1080 --rotate normal --right-of eDP1 &
mpd &
mpDris2 &
exec bspwm
