#! /bin/sh

sxhkd &

# set background
feh --bg-fill pix/1586068412407.png

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding		50
bspc config left_padding	50
bspc config right_padding	50
bspc config bottom_padding	50

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# start polybar
$HOME/.config/polybar/launch.sh
